//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hamroktmMainServer.Database.Public
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad_Images
    {
        public int Id { get; set; }
        public int AdId { get; set; }
        public string ImageName { get; set; }
        public int Position { get; set; }
    
        public virtual Ad Ad { get; set; }
    }
}
