//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hamroktmMainServer.Database.Public
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdComment
    {
        public int CommentId { get; set; }
        public string Description { get; set; }
        public int AdId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedById { get; set; }
    
        public virtual Ad Ad { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
